gitSourceBranch = "main"
changelog = true

# api docs ordering
[[classOrder]]
classes = ["Iris"]

[[classOrder]]
section = "Widgets"
classes = [
	"Window",
	"Menu",
	"Format",
	"Text",
	"Basic",
	"Tree",
    "Image",
	"Input",
	"Drag",
	"Slider",
	"Combo",
	"Plot",
	"Table",
]

[[classOrder]]
classes = ["State", "Internal"]

[docusaurus]
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"
copyright = "Copyright © 2024 Michael_48"
