name: Release

on:
  push:
    tags: ["v*"]

jobs:
  create-release:
    name: "Create Release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        run: gh release create ${{ github.ref_name }} --draft --verify-tag --title ${{ github.ref_name }} --notes ${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-files:
    needs: ["create-release"]
    name: "Build files"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: setup-aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: v0.3.0

      - name: Build files
        run: |
          rojo build -o Iris.rbxm ./default.project.json
          rojo build -o Iris.rbxl ./demo.project.json
          zip -r Iris.zip lib

      - name: Upload files
        run: |
          gh release upload ${{ github.ref_name }} ./Iris.rbxm ./Iris.rbxl ./Iris.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
